[package]
name = "change_songe_metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
lofty = "0.22.0"
rayon = "1.10.0"
taglib = "1.0.0"
zip = "2.2.2"
